# Generated by iptables-save v1.8.4 on Sun Oct 18 17:01:58 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Sun Oct 18 17:01:58 2020
# Generated by iptables-save v1.8.4 on Sun Oct 18 17:01:58 2020
*mangle
:PREROUTING ACCEPT [2930:880263]
:INPUT ACCEPT [2930:880263]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [2159:252244]
:POSTROUTING ACCEPT [2159:252244]
COMMIT
# Completed on Sun Oct 18 17:01:58 2020
# Generated by iptables-save v1.8.4 on Sun Oct 18 17:01:58 2020
*raw
:PREROUTING ACCEPT [2930:880263]
:OUTPUT ACCEPT [2159:252244]
COMMIT
# Completed on Sun Oct 18 17:01:58 2020
# Generated by iptables-save v1.8.4 on Sun Oct 18 17:01:58 2020
*security
:INPUT ACCEPT [2930:880263]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [2159:252244]
COMMIT
# Completed on Sun Oct 18 17:01:58 2020
# Generated by iptables-save v1.8.4 on Sun Oct 18 17:01:58 2020
*filter
:INPUT ACCEPT [786:74287]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [586:81733]
:sshguard - [0:0]
-A INPUT -p tcp -m multiport --dports 21,22 -j sshguard
COMMIT
# Completed on Sun Oct 18 17:01:58 2020
